### ISSUE TITLE
Вывод

### ISSUE THREAD

**Issue by Butonix** [Baltrunas/django-banners#4]
Подскажите? как вывести баннер на страницу
Invalid block tag on line 3: 'banner_one'. Did you forget to register or load this tag?

**Comment by Baltrunas** [comment]
{% load banners %}
{% banners 'group_slug' ['banners/default.html'] %}

**Comment by Butonix** [comment]
Вот так теперь ругается

Exception Value: | context must be a dict rather than Context.
-- | --

**Comment by Baltrunas** [comment]
Какая версия django и python? модуль давно не обновлялся возможно нужно править.

**Comment by Butonix** [comment]
Все стоит самое актуальное!
django 2.0.5
python 3.6.5
я так понял код устарел тут
`@register.simple_tag(takes_context=True)
def banners(context, group, tpl='banners/default.html'):
	try:
		page_url = context['request'].path_info
		site = context['request'].site
		group = BannerGroup.objects.get(slug=group)
		good_urls = []
		for url in URL.objects.filter(public=True, sites__in=[site]):
			if url.regex:
				url_re = re.compile(url.url)
				if url_re.findall(page_url):
					good_urls.append(url)
			elif page_url == url.url:
				good_urls.append(url)
		banners = Banner.objects.filter(public=True, group=group, urls__in=good_urls)
	except:
		banners = False
		group = False
	if(banners and group):
		context['banners'] = banners
		context['group'] = group

	t = template.loader.get_template(tpl)
	return t.render(template.Context(context))`

**Comment by Butonix** [comment]
Exception Value | name 'tpl_context' is not defined
-- | --

**Comment by Baltrunas** [comment]
def banners(context, group, tpl='banners/default.html'):
        **tpl_context = {}**
	try:

**Comment by Butonix** [comment]
ошибок нет? но баннер не вывелся
{% load banners %}
{% banners 'aside' %}

**Comment by Baltrunas** [comment]
sites подключен? проверять как домены настроены и url показа

**Comment by Butonix** [comment]
Да? подключен!
Сейчас скрины сделаю

**Comment by Butonix** [comment]
banner http://prntscr.com/jljhov <br>
url http://prntscr.com/jljhxn <br>
group http://prntscr.com/jljiau

**Comment by Baltrunas** [comment]
тут https://prnt.sc/jljhxn в url пропищи просто **/** домен и порт берутся с   sites

**Comment by Butonix** [comment]
к сожалению ничего не изменилось!

**Comment by Butonix** [comment]
точно так выводить?
{% banners 'aside' %}
не {% banner_group 'aside' %}

**Comment by Baltrunas** [comment]
точно banners, banner_group в шаблонном теге не осталось

**Comment by Butonix** [comment]
просто строчкой {% banners 'aside' %}
или <img =src="{% banners 'aside' %}">

**Comment by Butonix** [comment]
.py", line 15
    print('banners %s' % group)
        ^
IndentationError: expected an indented block
[23/May/2018 13:57:21] "GET / HTTP/1.1" 500 141268

**Comment by Butonix** [comment]
Exception Value: | Invalid block tag on line 35: 'banners', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
-- | --

**Comment by Baltrunas** [comment]
tpl_context так же добавить в строку после def banners(context, group, tpl='banners/default.html'):

**Comment by Baltrunas** [comment]
что в консоль то написало?

**Comment by Baltrunas** [comment]
после try: строку 		print(context['request'])
и опять вывод консоли

**Comment by Butonix** [comment]
banners aside
<WSGIRequest: GET '/'>
False
False

**Comment by Butonix** [comment]
banners aside
page_url: /
False
False

**Comment by Baltrunas** [comment]
очень похоже что sites недо подключен
    'django.contrib.sites', в INSTALLED_APPS ?
    'django.contrib.sites.middleware.CurrentSiteMiddleware', в MIDDLEWARE ?

**Comment by Butonix** [comment]
Да, ошибка!
Отсутствовал
'django.contrib.sites.middleware.CurrentSiteMiddleware',
Сейчас баннер вывелся!
Приогромное спасибо!

**Comment by Baltrunas** [comment]
принты подчистить не забудь

**Comment by Butonix** [comment]
@Baltrunas  Снова здравствуйте!
Столкнулся с проблемой
`MultipleObjectsReturned: get() returned more than one Banner -- it returned 2!`
В группе делаю 2 баннера и при выводе нет ротатора!

**Comment by Baltrunas** [comment]
А есть более подробный лог? сейчас остался только один шаблонный тег для вывода всей группы, нет ли групп с одинаковыми slug?
